name: Coverage and Security Report

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: xdebug

      - name: Install dependencies
        run: composer install

      - name: Run PHPUnit tests with coverage
        run: vendor/bin/phpunit --coverage-html docs/coverage

      - name: Upload Coverage Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: docs/coverage

      - name: Upload Semgrep Security Report artifact
        if: always()
        uses: actions/upload-pages-artifact@v2
        with:
          path: docs/seguridad

  deploy:
    needs: coverage
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
