name: Pruebas Mutacionales con Infection

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  infection:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer, phpunit

      - name: Instalar dependencias
        working-directory: web_ams
        run: composer install

      - name: Ejecutar Infection con reporte HTML
        working-directory: web_ams
        run: |
          composer require --dev infection/infection
          mkdir -p docs/seguridad
          vendor/bin/infection --ansi --no-interaction --logger-html=docs/seguridad/infection.html

      - name: Subir reporte a GH Pages o al repositorio
        working-directory: web_ams
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add docs/seguridad/infection.html
          git diff --cached --quiet || (git commit -m "chore: subir reporte Infection" && git push)
