name: Pruebas Mutacionales con Infection

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  infection:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer, phpunit

      - name: Instalar dependencias
        working-directory: web_ams
        run: composer install --ignore-platform-req=ext-mongodb

      - name: Instalar Infection (compatible con PHP 8.1)
        working-directory: web_ams
        run: composer require --dev infection/infection:^0.28 --ignore-platform-req=ext-mongodb

      - name: Ejecutar Infection
        working-directory: web_ams
        run: vendor/bin/infection --ansi --no-interaction
