name: Pruebas Mutacionales con Infection

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  infection:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-php-

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer, phpunit

      - name: Instalar dependencias
        working-directory: web_ams
        run: composer install --ignore-platform-req=ext-mongodb

      - name: Instalar Infection
        working-directory: web_ams
        run: composer require --dev infection/infection:^0.28 --ignore-platform-req=ext-mongodb

      - name: Ejecutar Infection y generar HTML
        working-directory: web_ams
        run: |
          mkdir -p docs/mutation-report
          vendor/bin/infection --logger-html=docs/mutation-report/index.html --ansi --no-interaction

      - name: Subir reporte de Infection a GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: web_ams/docs/mutation-report
