name: CI - Pruebas + Cobertura + Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    name: Ejecutar pruebas y cobertura
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, xml, mongodb
          coverage: xdebug

      - name: Instalar dependencias
        working-directory: web_ams
        run: composer install

      - name: Ejecutar PHPUnit con cobertura
        working-directory: web_ams
        run: vendor/bin/phpunit --coverage-html docs/coverage

      - name: Subir cobertura como artefacto
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: web_ams/docs/coverage

      - name: Subir cobertura para Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: web_ams/docs/coverage

  deploy:
    name: Deploy cobertura a GitHub Pages
    needs: test
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
