name: Terraform Apply

on:
  workflow_dispatch:

jobs:
  terraform:
    name: Despliegue de Infraestructura con Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Inicializar Terraform
        working-directory: infra
        run: terraform init

      - name: Validar configuración
        working-directory: infra
        run: terraform validate

      - name: Aplicar Terraform (crear EC2)
        working-directory: infra
        run: terraform apply -auto-approve -var="aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" -var="aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
